/*
 *  Copyright(c) 2000, 2009 arton
 *
 *  You may distribute under the terms of either the GNU General Public
 *  License
 *  $Date: 2006-11-03 04:23:11 +0900 (金, 03 11 2006) $
 */

import "oaidl.idl";
import "ocidl.idl";
import "activscp.idl";

[
	uuid(474067DF-D9CE-4324-9D3F-E81F8E011AD1),
	version(1.9),
	helpstring("Global Ruby Script 1.9")
]
library GRSCRIPTLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		object,
		uuid(0AC0D357-E866-11D3-8E82-0000F45A3C05),
	
		helpstring("IGlobalRubyScript Interface"),
		pointer_default(unique)
	]
	interface IGlobalRubyScript : IUnknown
	{
	};

	[
		object,
		uuid(0A4CBEBD-C46B-4A7C-A1E2-AD474C330C7A),
		dual,
		helpstring("rubyize other scripting object"),
		pointer_default(unique)
	]
	interface IRubyize : IDispatch
	{
		[id(1), propget] HRESULT Version([out, retval]BSTR* pVersion);
		[id(2), propget] HRESULT RubyVersion([out, retval]BSTR* pVersion);
		[id(10)] HRESULT rubyize([in]VARIANT val, [out, retval]VARIANT* pObj);
		[id(11)] HRESULT erubyize([in]BSTR script, [out, retval]VARIANT* pObj);
	};

	[
		uuid(0A383007-32FE-4ec0-97D6-59892ECD5413),
		helpstring("RubyScript Language (global)")
	]
	coclass GlobalRubyScript
	{
		[default] interface IGlobalRubyScript;
	};
	[
		uuid(63F6DE8D-85DF-4635-B8BF-04CE3EC5D2CC),
		helpstring("Rubyize Class")
	]
	coclass SimpleRubyize
	{
		[default] interface IRubyize;
	};
};
